name: CI

on:
  push:
  pull_request:

# Cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  # Run linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint
  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm test
